### ISSUE TITLE
SSR does not work correctly after upgrading to 2.0.0

### ISSUE THREAD

**Issue by JounQin** [ctrlplusb/react-async-bootstrapper#8]
Before upgrading, it will wait for API called even at the first time and render whole page, but after upgrading, no list content is renderer at the first time.

You can check https://github.com/JounQin/react-hackernews and run `yarn dev` and visit http://localhost:4000 to view the correct SSR page, then simply upgrade `react-async-bootstrapper` to `2.0.0`, then you will see incorrect page at first rendering.

Online Link: https://react-hn.now.sh/ (not upgrade yet)

I don't know if it is related to `react-async-bootstrapper@2.0.0` or `react-async-component@1.0.2` is not compatible with `react-async-bootstrapper@2.0.0`

**Comment by ctrlplusb** [comment]
Yep, `react-async-component` needs to be updated before that will work. It's in progress.

**Comment by ctrlplusb** [comment]
FYI, I have released an alpha version of react-async-component that works 👍

**Comment by hanaarena** [comment]
@ctrlplusb does the alpha version published to npm? it seem `bootstrap` still not works in SSR
